In [3]:
# When using SR data, please cite us and provide a link and/or a mention.
# https://www.pro-football-reference.com/boxscores/game-scores.htm

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm.notebook import trange, tqdm

In [8]:
# Pull the games data organized by box score

r = requests.get("https://www.pro-football-reference.com/boxscores/game-scores.htm")
soup = BeautifulSoup(r.text, 'html.parser')

In [9]:
# Create a list of URLs to scrape

# Test version where i manually downloaded the webpage
# with open("data/nfl_data/games_by_scores.html") as fp:
#     soup = BeautifulSoup(fp, 'html.parser')

url_list = []

for i in soup.find_all("table")[0].find_all(class_="center"):
    if i.a:
        url = "https://www.pro-football-reference.com" + i.a["href"]
        url_list.append(url)

In [10]:
box_scores_list = []

for i in tqdm(url_list):
    box_scores_list.append(pd.read_html(i)[0])


box_scores_output = pd.concat(box_scores_list)
box_scores_output

  0%|          | 0/1072 [00:00<?, ?it/s]

,Rk,Week,Day,Date,Unnamed: 4,Winner/tie,Unnamed: 6,Loser/tie,Unnamed: 8,PtsW,PtsL,YdsW,TOW,YdsL,TOL
0,1,5,Sun,1944-10-15,W,Cleveland Rams,@,Detroit Lions,boxscore,20,17,177.0,3.0,237.0,6.0
1,2,8,Sun,1947-11-09,W,Chicago Bears,NaN,Green Bay Packers,boxscore,20,17,320.0,9.0,299.0,4.0
2,3,15,Sun,1947-12-07,W,New York Yankees,@,Brooklyn Dodgers,boxscore,20,17,358.0,3.0,186.0,1.0
3,4,7,Sun,1951-11-11,W,Cleveland Browns,NaN,Philadelphia Eagles,boxscore,20,17,204.0,3.0,310.0,4.0
4,5,11,Sun,1951-12-09,W,Washington Redskins,@,Chicago Cardinals,boxscore,20,17,334.0,2.0,334.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1,6,Sun,1938-10-16,W,Washington Redskins,@,Detroit Lions,boxscore,7,5,0.0,0.0,0.0,0.0
0,1,7,Sun,1948-10-31,W,Washington Redskins,NaN,Boston Yanks,boxscore,59,21,625.0,5.0,333.0,8.0
0,1,12,Sun,1966-11-27,W,Washington Redskins,NaN,New York Giants,boxscore,72,41,341.0,2.0,389.0,6.0
0,1,9,Sun,1973-11-11,W,Washington Redskins,NaN,San Francisco 49ers,boxscore,33,9,343.0,2.0,322.0,5.0
0,1,5,Sun,1987-10-11,W,Washington Redskins,@,New York Giants,boxscore,38,12,376.0,2.0,171.0,3.0

In [11]:
box_scores_output.to_csv("data/nfl_data/nfl_box_scores.csv", index=False)